/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import Data_Access.BesoinData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Déchet;
import model.Utilisateur;
import Data_Access.DéchetData;
import Data_Access.HistoriqueData;
import Data_Access.ProduitDemandéData;
import java.util.Iterator;
import javax.swing.table.TableModel;
import model.ProduitDemandé;

/**
 *
 * @author Abdelhaq
 */
public class CréationBesoin extends javax.swing.JFrame {
    String format="dd/MM/yyyy";
    Utilisateur Actuel;
    
    /**
     * Creates new form DéclarationDéchets
     */
    public CréationBesoin() {
        initComponents();
        btnAjouter.setEnabled(false);
    }
    public CréationBesoin(Utilisateur utilisateur) {
        Actuel=utilisateur;
        initComponents();
        btnAjouter.setEnabled(false);
        labelID.setText(Actuel.getId()+"");
        DefaultTableModel defaultModel = (DefaultTableModel)jTable1.getModel();
        ArrayList<ProduitDemandé> list=BesoinData.getAll(Actuel);
        Iterator<ProduitDemandé> itr=list.iterator();
        while(itr.hasNext()){
            ProduitDemandé p=itr.next();
            defaultModel.addRow(new Object[]{p.getId(),p.getProduit(),p.getQuantité(),p.getDate()});
        }
    }
    public void validerChamps(){
        String produit=champProduit.getText();
        if(!produit.equalsIgnoreCase("")){
            btnAjouter.setEnabled(true);
        }
        
    }
    /*public boolean validerDate(){
       
        Date date=null;
        try {
            SimpleDateFormat sdf= new SimpleDateFormat(format);
            //date=sdf.parse(InputDate);
            if(!InputDate.equals(sdf.format(date))){
                date=null;
            }
        }catch (Exception e){
                e.printStackTrace();
        }
        return date!=null;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        champProduit = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 400));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Produit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        champProduit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        champProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                champProduitKeyReleased(evt);
            }
        });
        getContentPane().add(champProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 201, -1));

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Réinitialiser");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 370, 140));

        labelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelID.setText("ID");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Utilisateur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/900 x 800.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void champProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_champProduitKeyReleased
        // TODO add your handling code here:
        validerChamps();
    }//GEN-LAST:event_champProduitKeyReleased

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        ProduitDemandé produit=new ProduitDemandé();
        produit.setProduit(champProduit.getText());
        produit.setPropriétaire(Actuel.getId());
        BesoinData.ajouter(produit);
        this.dispose();
        new CréationBesoin(Actuel).setVisible(true);
        
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        int id=Integer.parseInt(model.getValueAt(i, 0).toString());
        String produit=model.getValueAt(i, 1).toString();
        String date=model.getValueAt(i, 2).toString();
        int a=JOptionPane.showConfirmDialog(null, "Voulez vous vraiment marquer le produit comme acquis ?","Selectionner",JOptionPane.YES_NO_OPTION);
        if(a==0){
           ProduitDemandéData.supprimer(id);
           this.dispose();
           new CréationBesoin(Actuel).setVisible(true);
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        champProduit.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CréationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CréationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CréationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CréationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CréationBesoin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFermer;
    private javax.swing.JTextField champProduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelID;
    // End of variables declaration//GEN-END:variables
}
