/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Déchet;
import model.Utilisateur;
import Data_Access.DéchetData;
import Data_Access.HistoriqueData;
import java.util.Iterator;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdelhaq
 */
public class DéclarationDéchets extends javax.swing.JFrame {

    String format = "dd/MM/yyyy";
    Utilisateur Actuel;

    /**
     * Creates new form DéclarationDéchets
     */
    public DéclarationDéchets() {
        initComponents();
        btnAjouter.setEnabled(false);
    }

    public DéclarationDéchets(Utilisateur utilisateur) {
        Actuel = utilisateur;
        initComponents();
        btnAjouter.setEnabled(false);
        labelID.setText(Actuel.getId() + "");
        DefaultTableModel defaultModel = (DefaultTableModel) jTable1.getModel();
        ArrayList<Déchet> list = DéchetData.getAll();
        Iterator<Déchet> itr = list.iterator();
        while (itr.hasNext()) {
            Déchet d = itr.next();
            defaultModel.addRow(new Object[]{d.getId(), d.getProduit(), d.getDate()});
        }
    }

    public void validerChamps() {

        String produit = champProduit.getText();
        if (!produit.equalsIgnoreCase("")) {
            btnAjouter.setEnabled(true);
        }

    }

    public boolean validerDate() {
        String InputDate = champDate.getText();
        Date date = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            date = sdf.parse(InputDate);
            if (!InputDate.equals(sdf.format(date))) {
                date = null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer la date en format dd/MM/yyyy ", "Selectionner", JOptionPane.ERROR_MESSAGE);
        }
        return date != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        champProduit = new javax.swing.JTextField();
        champDate = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Produit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        champProduit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        champProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                champProduitKeyReleased(evt);
            }
        });
        getContentPane().add(champProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 201, -1));

        champDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        champDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                champDateKeyReleased(evt);
            }
        });
        getContentPane().add(champDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 205, -1));

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-new.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eraser.png"))); // NOI18N
        btnClear.setText("Réinitialiser");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produit", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 264, 140));

        labelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelID.setText("jLabel3");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Utilisateur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_new.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void champProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_champProduitKeyReleased
        // TODO add your handling code here:
        validerChamps();
    }//GEN-LAST:event_champProduitKeyReleased

    private void champDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_champDateKeyReleased
        // TODO add your handling code here:
        validerChamps();
    }//GEN-LAST:event_champDateKeyReleased

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        if (validerDate()) {
            Déchet déchet = new Déchet();
            déchet.setProduit(champProduit.getText());
            déchet.setProprétaire(Actuel.getId());
            déchet.setDate(champDate.getText());
            DéchetData.ajouter(déchet);
            this.dispose();
            new DéclarationDéchets(Actuel).setVisible(true);
        }


    }//GEN-LAST:event_btnAjouterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        String produit = model.getValueAt(i, 1).toString();
        String date = currentDate();
        int a = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment marquer le produit comme vendu ?", "Selectionner", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            HistoriqueData.ajouter(produit, date);
            DéchetData.supprimer(id);
            this.dispose();
            new DéclarationDéchets(Actuel).setVisible(true);
        }


    }//GEN-LAST:event_jTable1MouseClicked
    public String currentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String date = sdf.format(new Date());
        return date;
    }
    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        champProduit.setText("");
        champDate.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DéclarationDéchets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DéclarationDéchets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DéclarationDéchets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DéclarationDéchets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DéclarationDéchets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFermer;
    private javax.swing.JTextField champDate;
    private javax.swing.JTextField champProduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelID;
    // End of variables declaration//GEN-END:variables
}
