/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import Data_Access.BesoinData;
import Data_Access.ProduitDemandéData;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.ProduitDemandé;
import model.Utilisateur;

/**
 *
 * @author Abdelhaq
 */
public class DéclarationBesoin extends javax.swing.JFrame {

    ArrayList<ProduitDemandé> listBesoins;
    String format = "dd/MM/yyyy";
    Utilisateur Actuel;

    /**
     * Creates new form DéclarationBesoin
     */
    public DéclarationBesoin() {
        initComponents();
    }

    public DéclarationBesoin(Utilisateur utilisateur) {
        initComponents();
        Actuel = utilisateur;
        btnDéclarerBesoin.setEnabled(false);
        btnClear.setEnabled(false);
        DefaultTableModel defaultModel = (DefaultTableModel) tableAll.getModel();
        ArrayList<ProduitDemandé> list = BesoinData.getAll(Actuel);
        Iterator<ProduitDemandé> itr = list.iterator();
        while (itr.hasNext()) {
            ProduitDemandé p = itr.next();
            defaultModel.addRow(new Object[]{p.getProduit()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAll = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDemandés = new javax.swing.JTable();
        btnAjouter = new javax.swing.JButton();
        btnCréerBesoin = new javax.swing.JButton();
        btnDéclarerBesoin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAll.setRowHeight(30);
        jScrollPane1.setViewportView(tableAll);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 17, 227, 109));

        tableDemandés.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Quantité", "Date"
            }
        ));
        tableDemandés.setRowHeight(50);
        jScrollPane2.setViewportView(tableDemandés);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 688, 163));

        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-new.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 144, -1, -1));

        btnCréerBesoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/create-new-folder.png"))); // NOI18N
        btnCréerBesoin.setText("Créer Besoin");
        btnCréerBesoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCréerBesoinActionPerformed(evt);
            }
        });
        getContentPane().add(btnCréerBesoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 144, -1, -1));

        btnDéclarerBesoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/announce.png"))); // NOI18N
        btnDéclarerBesoin.setText("Déclarer Besoin");
        btnDéclarerBesoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDéclarerBesoinActionPerformed(evt);
            }
        });
        getContentPane().add(btnDéclarerBesoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eraser.png"))); // NOI18N
        btnClear.setText("Réinitialiser");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/900 x 800.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        btnDéclarerBesoin.setEnabled(true);
        btnClear.setEnabled(true);
        int index = tableAll.getSelectedRow();
        DefaultTableModel dtm1 = (DefaultTableModel) tableAll.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) tableDemandés.getModel();

        String produit = dtm1.getValueAt(index, 0).toString();
        dtm2.addRow(new Object[]{produit});

    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnCréerBesoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCréerBesoinActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CréationBesoin().setVisible(true);
    }//GEN-LAST:event_btnCréerBesoinActionPerformed

    private void btnDéclarerBesoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDéclarerBesoinActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultModel = (DefaultTableModel) tableDemandés.getModel();
        for (int i = 0; i < defaultModel.getRowCount(); i++) {
            String date = defaultModel.getValueAt(i, 2).toString();
            String produit = defaultModel.getValueAt(i, 0).toString();
            //int quantité = Integer.parseInt(dtm.getValueAt(i, 1).toString());
            String quantité = defaultModel.getValueAt(i, 1).toString();
            if (validerDate(date)) {
                ProduitDemandé p = new ProduitDemandé();
                p.setProduit(produit);
                p.setQuantité(quantité);
                p.setDate(date);
                p.setPropriétaire(Actuel.getId());
                ProduitDemandéData.ajouter(p);
            }

        }
    }//GEN-LAST:event_btnDéclarerBesoinActionPerformed
    public boolean validerDate(String InputDate) {
//        String InputDate = champDate.getText();
        Date date = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            date = sdf.parse(InputDate);
            if (!InputDate.equals(sdf.format(date))) {
                date = null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer la date en format dd/MM/yyyy ", "Selectionner", JOptionPane.ERROR_MESSAGE);
        }
        return date != null;
    }
    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultModel = (DefaultTableModel) tableDemandés.getModel();
        for (int i = 0; i < defaultModel.getRowCount(); i++) {
            defaultModel.removeRow(i);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DéclarationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DéclarationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DéclarationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DéclarationBesoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DéclarationBesoin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCréerBesoin;
    private javax.swing.JButton btnDéclarerBesoin;
    private javax.swing.JButton btnFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAll;
    private javax.swing.JTable tableDemandés;
    // End of variables declaration//GEN-END:variables
}
