/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import Data_Access.UtilisateurData;
import javax.swing.JOptionPane;
import model.Utilisateur;

/**
 *
 * @author Abdelhaq
 */
public class FormUtilisateur extends javax.swing.JFrame {
    Utilisateur concerné;
    /**
     * Creates new form FormUtilisateur
     */
    public FormUtilisateur() {
        initComponents();

    }

    public FormUtilisateur(Utilisateur utilisateur) {
        initComponents();
        concerné=utilisateur;
        champNom.setText(utilisateur.getNom());
        champPrénom.setText(utilisateur.getPrénom());
        champEmail.setText(utilisateur.getEmail());
        champMdp.setText(utilisateur.getMdp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        champNom = new javax.swing.JTextField();
        champPrénom = new javax.swing.JTextField();
        champEmail = new javax.swing.JTextField();
        champMdp = new javax.swing.JTextField();
        choixRole = new javax.swing.JComboBox<>();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/small_page.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Prénom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 89, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 127, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mot de passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 171, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Rôle");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 215, -1, -1));

        champNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(champNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 42, 199, -1));

        champPrénom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(champPrénom, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 86, 199, -1));

        champEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(champEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 124, 199, -1));

        champMdp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(champMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 168, 199, -1));

        choixRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        choixRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable  restaurant", "Responsable point de vente" }));
        choixRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixRoleActionPerformed(evt);
            }
        });
        getContentPane().add(choixRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 212, 199, -1));

        btnValider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        getContentPane().add(btnValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        btnAnnuler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_new_small.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixRoleActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir modifier ?", "Selectionner", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            concerné.setNom(champNom.getText());
            concerné.setPrénom(champPrénom.getText());
            concerné.setEmail(champEmail.getText());
            concerné.setMdp(champMdp.getText());
            concerné.setRôle((String) choixRole.getSelectedItem());
            UtilisateurData.modifier(concerné);
            this.dispose();
            new GestionComptes().setVisible(true);
        }


    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnValider;
    private javax.swing.JTextField champEmail;
    private javax.swing.JTextField champMdp;
    private javax.swing.JTextField champNom;
    private javax.swing.JTextField champPrénom;
    private javax.swing.JComboBox<String> choixRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
