/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import Data_Access.ProduitDemandéData;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.ProduitDemandé;

/**
 *
 * @author Abdelhaq
 */
public class GestionBesoins extends javax.swing.JFrame {

    /**
     * Creates new form GestionBesoins
     */
    public GestionBesoins() {
        initComponents();
        btnValider.setEnabled(false);
        btnSupprimer.setEnabled(false);
        DefaultTableModel defaultModel = (DefaultTableModel)tableBesoinsDéclarés.getModel();
        ArrayList<ProduitDemandé> list=new ArrayList<>();
        list=ProduitDemandéData.getAll();
        Iterator<ProduitDemandé> itr=list.iterator();
        while(itr.hasNext()){
            ProduitDemandé pr=itr.next();
            defaultModel.addRow(new Object[]{pr.getId(),pr.getProduit(),pr.getQuantité(),pr.getDate(),pr.getPropriétaire(),pr.getEtat()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBesoinsDéclarés = new javax.swing.JTable();
        btnValider = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBesoinsDéclarés.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "produit", "quantité", "date", "propriétaire", "etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBesoinsDéclarés.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBesoinsDéclarésMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBesoinsDéclarés);
        if (tableBesoinsDéclarés.getColumnModel().getColumnCount() > 0) {
            tableBesoinsDéclarés.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableBesoinsDéclarés.getColumnModel().getColumn(2).setPreferredWidth(5);
            tableBesoinsDéclarés.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 53, 650, 281));

        btnValider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btnValider.setText("Valider Besoin");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        getContentPane().add(btnValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnSupprimer.setText("Supprimer Besoin");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_new.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableBesoinsDéclarésMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBesoinsDéclarésMouseClicked
        // TODO add your handling code here:
        btnValider.setEnabled(true);
        btnSupprimer.setEnabled(true);
        
    }//GEN-LAST:event_tableBesoinsDéclarésMouseClicked

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        ProduitDemandé pr=new ProduitDemandé();
        int row = tableBesoinsDéclarés.getSelectedRow();
        int c= JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir valider le besoin ?","Selectionner",JOptionPane.YES_NO_OPTION);
        if(c==0){
            tableBesoinsDéclarés.setValueAt("validé", row, 5);
            int id=Integer.parseInt(tableBesoinsDéclarés.getValueAt(row, 0).toString());
            String nomProduit=tableBesoinsDéclarés.getValueAt(row, 1).toString();
            String quantité=tableBesoinsDéclarés.getValueAt(row, 2).toString();
            String date=tableBesoinsDéclarés.getValueAt(row, 3).toString();
            int propriétaire=Integer.parseInt(tableBesoinsDéclarés.getValueAt(row, 4).toString()) ;
            String etat=tableBesoinsDéclarés.getValueAt(row, 5).toString();
            pr.setId(id);
            pr.setProduit(nomProduit);
            pr.setQuantité(quantité);
            pr.setDate(date);
            pr.setPropriétaire(propriétaire);
            pr.setEtat(etat);
            ProduitDemandéData.modifier(pr);
        }
            
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        ProduitDemandé pr=new ProduitDemandé();
        int row = tableBesoinsDéclarés.getSelectedRow();
        DefaultTableModel defaultModel =(DefaultTableModel) tableBesoinsDéclarés.getModel();
        int c= JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir Supprimer le besoin ?","Selectionner",JOptionPane.YES_NO_OPTION);
        if(c==0){
            int id=Integer.parseInt(tableBesoinsDéclarés.getValueAt(row, 0).toString());
//            String nomProduit=tableBesoinsDéclarés.getValueAt(row, 1).toString();
//            int quantité=Integer.parseInt(tableBesoinsDéclarés.getValueAt(row, 2).toString());
//            String date=tableBesoinsDéclarés.getValueAt(row, 3).toString();
//            int propriétaire=Integer.parseInt(tableBesoinsDéclarés.getValueAt(row, 4).toString()) ;
//            String etat=tableBesoinsDéclarés.getValueAt(row, 5).toString();
            pr.setId(id);
            defaultModel .removeRow(row);
//            pr.setProduit(nomProduit);
//            pr.setQuantité(quantité);
//            pr.setDate(date);
//            pr.setPropriétaire(propriétaire);
//            pr.setEtat(etat);
            ProduitDemandéData.supprimer(pr.getId());
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionBesoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionBesoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionBesoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionBesoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionBesoins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnValider;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBesoinsDéclarés;
    // End of variables declaration//GEN-END:variables
}
