/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import model.Utilisateur;

/**
 *
 * @author Abdelhaq
 */
public class HomeRestau extends javax.swing.JFrame {
    Utilisateur Actuel;
    /**
     * Creates new form Home
     */
    public HomeRestau() {
        initComponents();
    }
    public HomeRestau(Utilisateur utilisateur){
        Actuel=utilisateur;
        initComponents();
        System.out.println(Actuel.getPrénom());
        labelNomEtPrenom.setText(Actuel.getNom()+" "+Actuel.getPrénom());
        labelEmail.setText(Actuel.getEmail());
        labelRôle.setText(Actuel.getRôle());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnDeclarerDechet = new javax.swing.JButton();
        btnHistorique = new javax.swing.JButton();
        btnMessageVente = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        btnPtVente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNomEtPrenom = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelRôle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 770));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 770));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(226, 220, 221));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeclarerDechet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeclarerDechet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash_food.png"))); // NOI18N
        btnDeclarerDechet.setText("Déclarer déchets");
        btnDeclarerDechet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclarerDechetActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeclarerDechet, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 251, 340, -1));

        btnHistorique.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHistorique.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/history.png"))); // NOI18N
        btnHistorique.setText("Visualiser l'historique");
        btnHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriqueActionPerformed(evt);
            }
        });
        jPanel3.add(btnHistorique, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 365, -1, -1));

        btnMessageVente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMessageVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Messagerie_big.png"))); // NOI18N
        btnMessageVente.setText("Messagerie");
        btnMessageVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageVenteActionPerformed(evt);
            }
        });
        jPanel3.add(btnMessageVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 340, -1));

        btnFermer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        jPanel3.add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        btnPtVente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPtVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/point_vente.png"))); // NOI18N
        btnPtVente.setText("Points de vente");
        btnPtVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPtVenteActionPerformed(evt);
            }
        });
        jPanel3.add(btnPtVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 605, 330, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1080, 770));

        jPanel2.setBackground(new java.awt.Color(60, 0, 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENUE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        labelNomEtPrenom.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        labelNomEtPrenom.setForeground(new java.awt.Color(255, 255, 255));
        labelNomEtPrenom.setText("Nom et Prénom");
        jPanel2.add(labelNomEtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Email");
        jPanel2.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        labelRôle.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        labelRôle.setForeground(new java.awt.Color(255, 255, 255));
        labelRôle.setText("Rôle");
        jPanel2.add(labelRôle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogout.setText("Déconnexion");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPtVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPtVenteActionPerformed
        // TODO add your handling code here:
        new PointVente(Actuel).setVisible(true);
    }//GEN-LAST:event_btnPtVenteActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnMessageVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageVenteActionPerformed
        // TODO add your handling code here:
        new Messagerie(Actuel).setVisible(true);
    }//GEN-LAST:event_btnMessageVenteActionPerformed

    private void btnHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriqueActionPerformed
        // TODO add your handling code here:
        new Historique(Actuel).setVisible(true);
    }//GEN-LAST:event_btnHistoriqueActionPerformed

    private void btnDeclarerDechetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclarerDechetActionPerformed
        // TODO add your handling code here:
        new DéclarationDéchets(Actuel).setVisible(true);
    }//GEN-LAST:event_btnDeclarerDechetActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeRestau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeRestau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeRestau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeRestau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeRestau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeclarerDechet;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnHistorique;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMessageVente;
    private javax.swing.JButton btnPtVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNomEtPrenom;
    private javax.swing.JLabel labelRôle;
    // End of variables declaration//GEN-END:variables
}
