/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetb;

import Data_Access.PtVenteData;
import Data_Access.UtilisateurData;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import model.PtVente;
import model.Utilisateur;

/**
 *
 * @author Abdelhaq
 */
public class PointVente extends javax.swing.JFrame {
    Utilisateur actuel;
    /**
     * Creates new form PointVente
     */
    public PointVente() {
        initComponents();
        btnEnvoyerMsg.setEnabled(false);
        ArrayList<PtVente> list=new ArrayList<>();
        DefaultTableModel defaultModel=(DefaultTableModel) tableauPtVente.getModel();
        list=PtVenteData.getALl(actuel);
        Iterator<PtVente> itr=list.iterator();
        while(itr.hasNext()){
            PtVente p=itr.next();
            defaultModel.addRow(new Object[]{p.getResponsable().getId(),p.getResponsable().getNom()+" "+p.getResponsable().getPrénom(),p.getProduit().getDate(),p.besoins.toString()});
        }
    }
    public PointVente(Utilisateur u) {
        initComponents();
        actuel=u;
        btnEnvoyerMsg.setEnabled(false);
        ArrayList<PtVente> list=new ArrayList<>();
        DefaultTableModel defaultModel=(DefaultTableModel) tableauPtVente.getModel();
        list=PtVenteData.getALl(actuel);
        Iterator<PtVente> itr=list.iterator();
        while(itr.hasNext()){
            PtVente p=itr.next();
            defaultModel.addRow(new Object[]{p.getResponsable().getId(),p.getResponsable().getNom()+" "+p.getResponsable().getPrénom(),p.getProduit().getDate(),p.besoins.toString()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableauPtVente = new javax.swing.JTable();
        btnEnvoyerMsg = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableauPtVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pt de vente", "Propriétaire", "Date limite", "Besoin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableauPtVente.setRowHeight(30);
        tableauPtVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauPtVenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableauPtVente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 600, 290));

        btnEnvoyerMsg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnvoyerMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/message.png"))); // NOI18N
        btnEnvoyerMsg.setText("Envoyer Message");
        btnEnvoyerMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerMsgActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnvoyerMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close _2.png"))); // NOI18N
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });
        getContentPane().add(btnFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_new.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvoyerMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerMsgActionPerformed
        // TODO add your handling code here:
        Utilisateur destinataire;
        int row=tableauPtVente.getSelectedRow();
        int id=(int) tableauPtVente.getValueAt(row, 0);
        System.out.println(id);
        destinataire=UtilisateurData.trouver(id);
        new Messages(actuel,destinataire).setVisible(true);
    }//GEN-LAST:event_btnEnvoyerMsgActionPerformed

    private void tableauPtVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauPtVenteMouseClicked
        // TODO add your handling code here:
        btnEnvoyerMsg.setEnabled(true);
    }//GEN-LAST:event_tableauPtVenteMouseClicked

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointVente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoyerMsg;
    private javax.swing.JButton btnFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableauPtVente;
    // End of variables declaration//GEN-END:variables
}
